project:
  type: website

website:
  page-navigation: true
  title: "STA 221 - Spring 2026"
  description: "Homepage for STA 221 - Regression Analysis: Theory and Applications at Duke University, Spring 2026"
  site-url: https://sta221-sp26.netlify.app

  repo-url: https://github.com/sta221-sp26/website
  repo-actions: [issue]
  
  page-footer:
    background: "#497E99"
    left: |
      &copy; Copyright 2026, Maria Tackett
    right: |
      This site is built with [Quarto](https://quarto.org/)

  sidebar:
    background: "#407E99"
    logo: "images/logo.png"
    align: center
    tools: 
      - icon: github
        href: https://github.com/sta221-sp26
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: chat-dots-fill
        href: https://edstem.org/us/courses/90766
        text: Ed Discussion
      - icon: check-square-fill
        menu:
          - text: Canvas
            url: https://canvas.duke.edu/courses/73984
          - text: Gradescope
            url: https://www.gradescope.com/courses/1209604
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: overview.qmd
        text: Overview
      - href: syllabus.qmd
        text: Syllabus
      - href: support.qmd
        text: Support
      - href: index.qmd
        text: Schedule 
      - section: Computing
        contents: 
        - href: computing-access.qmd
          text: Access
        - href: computing-troubleshooting.qmd
          text: Troubleshooting
        - href: computing-r-resources.qmd
          text: R resources
      - section: Homework
        contents:
        - href: hw/hw-01.qmd
          text: HW 01
        - href: hw/hw-02.qmd
          text: HW 02
        - href: hw/hw-03.qmd
          text: HW 03
        - href: hw/hw-04.qmd
          text: HW 04
        - href: hw/stats-experience.qmd
          text: Statistics experience
      - section: Labs
        contents: 
        - href: labs/lab-00.qmd
          text: Lab 00
        - href: labs/lab-01.qmd
          text: Lab 01
        - href: labs/lab-02.qmd
          text: Lab 02
        - href: labs/lab-03.qmd
          text: Lab 03
        - href: labs/lab-04.qmd
          text: Lab 04
        - href: labs/lab-05.qmd
          text: Lab 05
        - href: labs/lab-06.qmd
          text: Lab 06
        - href: labs/lab-07.qmd
          text: Lab 07
      - section: Project
        contents:
        - href: project.qmd
          text: Instructions
        - href: project-tips.qmd
          text: Tips + resources
      - href: links.qmd
        text: Useful links
      - href: https://forms.office.com/r/RW2TTPrsQq
        text: Lecture recording request
    #  - href: exam-01-practice.qmd
     #   text: Exam 01 Practice
     # - href: exam-02-practice.qmd
     #   text: Exam 02 Practice
   #   - href: https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=0b5392d5-d61b-465a-80eb-b25e014a75a9
    #    text: Lecture recordings
   #   - href: math-rules.qmd
    #    text: Math rules
        

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: visual    
    



